### PR TITLE
Add a better parallax

### PR DESCRIPTION
**Pull request by JortvD**
Add a few extra layers for a better looking parallax effect

### CODE REVIEW

**Comment by LukeGarrigan** [comment]
I don't love it to be honest mate, the background is black and doesn't look as nice as the dark bluey it already was.

**Comment by JortvD** [comment]
Oh, I might have removed the background color while adding the multi layer functionality. I'll change the background and remove some of the stars.

**Comment by JortvD** [comment]
What do you think now?

**Comment by LukeGarrigan** [comment]
Yeah I really like that, good job mate, thank you!

**Comment by JortvD** [comment]
No problem

**Pull request merged**
